### ISSUE TITLE
Проблемы с запуском

### ISSUE THREAD

**Issue by artem-malko** [CSSSR/csssr-project-template#114]
Выполнил первые 3 шага из доки:
* git clone
* npm i
* npm start 

Вот такой лог выдало:
```bash
~/Work/new-project master= $ npm start

> csssr-project-template@0.25.0 start /Users/a.malko/Work/new-project
> gulp --debug

[13:09:12] Failed to load external module babel-register
[13:09:12] Requiring external module babel-core/register
module.js:327
    throw err;
    ^

Error: Cannot find module 'stylus'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/a.malko/Work/new-project/node_modules/stylus-import-if-exist/dist/index.js:7:15)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/a.malko/Work/new-project/node_modules/babel-core/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (styles.js:7:1)
    at Module._compile (module.js:409:26)
    at loader (/Users/a.malko/Work/new-project/node_modules/babel-core/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/a.malko/Work/new-project/node_modules/babel-core/node_modules/babel-register/lib/node.js:136:7)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! csssr-project-template@0.25.0 start: `gulp --debug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the csssr-project-template@0.25.0 start script 'gulp --debug'.
npm ERR! This is most likely a problem with the csssr-project-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --debug
npm ERR! You can get their info via:
npm ERR!     npm owner ls csssr-project-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/a.malko/Work/new-project/npm-debug.log
```

OS X 10.11.3 Node 4.3.1, npm 2.14.12

**Comment by in-in** [comment]
Есть возможность npm посвежее поставить?
https://github.com/CSSSR/csssr-project-template/issues/89

**Comment by jt3k** [comment]
стоит ли глобально стилус ?

возможно, что бабель в галпе не может отрезолвить стилус

**Comment by dzhiriki** [comment]
Собственно, не может отрезолвить по той причине, что `stylus-import-if-exist` не имеет в зависимостях `stylus`.
Не имеет он его потому, чтобы версия, которая используется в проекте не отличалась от версии, которая используется в плагине.
Т.е. плагин ожидает, что стайлус будет стоять как пакет уровнем выше. Но старый нпм не ставит пакеты плоским списком, а значит у плагина доступа к стайлусу не будет.
Потому и ошибка.

**Comment by artem-malko** [comment]
@dzhiriki @jt3k @in-in ребят, в таком случае вам стоит это указать хотя бы в доке. Нигде же это не сказано. Вообще, лучше всего это указать в engines, в package.json, что требуется npm 3 и выше. Я крайне удивлен, что никто больше с такой проблемой не обращался.
Естественно из логов все ясно, кто виноват и что можно поделать, но выглядит очень странно, что он требует stylus, как отдельный пакет, в то время, как в package.json его нет. В общем, считаю, что этот момент надо как-то раскрыть подробнее или предупреждать на стадии установки еще.

**Comment by Nitive** [comment]
В engines указано `"node": ">=5.1.0"`, а пятая нода требует npm 3.
Все же лучше добавить stylus в devDependencies. @dzhiriki, есть возражения?

**Comment by artem-malko** [comment]
@Nitive убирать поддержку 4 ноды - странное решение. Это же lts версия.

**Comment by iamstarkov** [comment]
Пятая нода не требует нпм3, она только по умолчанию с ним идёт. Сдаунгрейдить его никто мешает

**Comment by jt3k** [comment]
`npm i -g npm`

**Comment by Nitive** [comment]
@iamstarkov Спасибо, не знал.

**Comment by iamstarkov** [comment]
> Все же лучше добавить stylus в devDependencies. @dzhiriki, есть возражения?

@Nitive а добавление стилуса как полноценную зависимость всё ещё можно добавить?

**Comment by Nitive** [comment]
@iamstarkov #151

**Comment by artem-malko** [comment]
@iamstarkov @Nitive забавные вы ребята, чтобы на ишью обратили внимание — это ишью надо закрыть)
