### ISSUE TITLE
Ошибка в таске styles:lint

### ISSUE THREAD

**Issue by kuflash** [CSSSR/csssr-project-template#125]
Получаю такую ошибку при сборке, когда есть ошибки линтера в стилях
```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: path must be a string
    at Module.require (module.js:365:3)
    at require (module.js:385:17)
    at Object.init (/Users/kuflash/csssr/csssr-project-template/node_modules/stylint/src/core/init.js:32:19)
    at /Users/kuflash/csssr/csssr-project-template/node_modules/stampit/stampit.js:88:25
    at forEach (/Users/kuflash/csssr/csssr-project-template/node_modules/mout/array/forEach.js:15:27)
    at Function.factory [as create] (/Users/kuflash/csssr/csssr-project-template/node_modules/stampit/stampit.js:86:7)
    at DestroyableTransform._transform (/Users/kuflash/csssr/csssr-project-template/node_modules/gulp-stylint/index.js:81:5)
    at DestroyableTransform.Transform._read (/Users/kuflash/csssr/csssr-project-template/node_modules/gulp-stylint/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/kuflash/csssr/csssr-project-template/node_modules/gulp-stylint/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/kuflash/csssr/csssr-project-template/node_modules/gulp-stylint/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/kuflash/csssr/csssr-project-template/node_modules/gulp-stylint/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/kuflash/csssr/csssr-project-template/node_modules/gulp-stylint/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/kuflash/csssr/csssr-project-template/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/kuflash/csssr/csssr-project-template/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/kuflash/csssr/csssr-project-template/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
```

**Comment by iamstarkov** [comment]
you might want to create a pull-request with dat commit
