### ISSUE TITLE
fatal error: 'util-inl.h' file not found #include "util-inl.h"

### ISSUE THREAD

**Issue by AdreeUA** [CSSSR/csssr-project-template#131]
При установке проекта выдает ошибку

```
> buffertools@2.1.3 install /Users/adree/Project/csssr-project-template-master 2/node_modules/buffertools
> node-gyp rebuild

  CXX(target) Release/obj.target/buffertools/buffertools.o
  SOLINK_MODULE(target) Release/buffertools.node

> fsevents@1.0.11 install /Users/adree/Project/csssr-project-template-master 2/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/adree/Project/csssr-project-template-master 2/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote

> node-zlib-backport@0.11.15 install /Users/adree/Project/csssr-project-template-master 2/node_modules/node-zlib-backport
> node-gyp rebuild

  CXX(target) Release/obj.target/zlib/src/node_zlib.o
In file included from ../src/node_zlib.cc:32:
/Users/adree/.node-gyp/5.10.1/include/node/node_internals.h:6:10: fatal error: 'util-inl.h' file not found
#include "util-inl.h"
         ^
1 error generated.
make: *** [Release/obj.target/zlib/src/node_zlib.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/adree/Project/csssr-project-template-master 2/node_modules/node-zlib-backport
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:node-zlib-backport@0.11.15 node-zlib-backport@0.11.15 install: `node-gyp rebuild`
npm WARN install:node-zlib-backport@0.11.15 Exit status 1
```

**Comment by iamstarkov** [comment]
какая-то бинарная зависимость не собралась

**Comment by iamstarkov** [comment]
fsevents

**Comment by iamstarkov** [comment]
это не проблема этого проекта

**Comment by iamstarkov** [comment]
похоже на эту проблему https://github.com/strongloop/fsevents/issues/122 (единственный открытый ишью про "unable to build")

**Comment by iamstarkov** [comment]
хотя мб нужно обновить зависимости

**Comment by iamstarkov** [comment]
@felixexter я могу сделать пр с david бейджами https://david-dm.org/CSSSR/csssr-project-template#info=devDependencies&view=table
+ я бы посоветовал включить greenkeeper

**Comment by jt3k** [comment]
Для гринкипера нужны CI тесты. А у нас их нет.

**Comment by AdreeUA** [comment]
Обновил зависимости как Вы говорили , появилась ошибка таска. Вернул все обратно, но ошибка осталась =(
```
11:47:38] SyntaxError: Unexpected token ]
    at Object.parse (native)
    at Object.checkBabel (/Users/adree/Project/portfolio/node_modules/npm-install-webpack-plugin/src/installer.js:83:11)
    at new NpmInstallPlugin (/Users/adree/Project/portfolio/node_modules/npm-install-webpack-plugin/src/plugin.js:35:13)
    at makeWebpackConfig (webpack.conf.js:74:4)
    at runWebpack (scripts.js:13:24)
    at Gulp.<anonymous> (scripts.js:32:9)
    at module.exports (/Users/adree/Project/portfolio/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/adree/Project/portfolio/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/adree/Project/portfolio/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/adree/Project/portfolio/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (watch.js:19:7)
    at module.exports (/Users/adree/Project/portfolio/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/adree/Project/portfolio/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/adree/Project/portfolio/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/adree/Project/portfolio/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/adree/Project/portfolio/node_modules/run-sequence/index.js:88:16)
    at Gulp.onTaskEnd (/Users/adree/Project/portfolio/node_modules/run-sequence/index.js:77:5)
    at emitOne (events.js:95:20)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/adree/Project/portfolio/node_modules/orchestrator/index.js:264:8)
    at /Users/adree/Project/portfolio/node_modules/orchestrator/index.js:275:23
    at finish (/Users/adree/Project/portfolio/node_modules/orchestrator/lib/runTask.js:21:8)
[11:47:38] Error in plugin 'run-sequence'
Message:
    An error occured in task 'scripts:watch'.
[11:47:38] Finished 'watch' after 53 ms

```

**Comment by jt3k** [comment]
i have no idea

**Comment by iamstarkov** [comment]
сейчас проблема выглядит так как будто где-то синтаксическая ошибка. надо дебажить галп-файл так как ошибка вылетела оттуда

**Comment by AdreeUA** [comment]
C таском я разобрался, но первая ошибка постоянно вылетает, какой бы пакет из NPM  я не ставил

**Comment by iamstarkov** [comment]
я почти уверен, что это не проблема шаблона. @AdreeUA ты смотрел открытые ишью у используемых инструментов. возможно проблема уже описана

**Comment by AdreeUA** [comment]
Я искал в инете, но не могу понять что мне нужно сделать? https://github.com/nodejs/node-gyp/issues/782 Не поможете разобраться?

**Comment by felixexter** [comment]
Закрою, дискуссия продолжилась в #135
