### ISSUE TITLE
Сбой после установки

### ISSUE THREAD

**Issue by mathetes** [CSSSR/csssr-project-template#183]
Сразу после установки сборки при запуске получаю сбой из-за синтаксической ошибки (в терминале галочки ^^^^^^ стоят под словом import):

`[08:55:57] Requiring external module babel-register
/media/mathetes/Данные/02_DEV/allApps/03.0_GULP/csssr1116/node_modules/spritesmith-dir-checker/index.js:1
(function (exports, require, module, __filename, __dirname) { import fs from 'fs';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .js] (/media/mathetes/Данные/02_DEV/allApps/03.0_GULP/csssr1116/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/media/mathetes/Данные/02_DEV/allApps/03.0_GULP/csssr1116/tasks/sprites.js:4:1)
    at Module._compile (module.js:410:26)
    at loader (/media/mathetes/Данные/02_DEV/allApps/03.0_GULP/csssr1116/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/media/mathetes/Данные/02_DEV/allApps/03.0_GULP/csssr1116/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireDir (/media/mathetes/Данные/02_DEV/allApps/03.0_GULP/csssr1116/node_modules/require-dir/index.js:122:33)
    at Object.<anonymous> (/media/mathetes/Данные/02_DEV/allApps/03.0_GULP/csssr1116/gulpfile.babel.js:3:1)
    at Module._compile (module.js:410:26)
    at loader (/media/mathetes/Данные/02_DEV/allApps/03.0_GULP/csssr1116/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/media/mathetes/Данные/02_DEV/allApps/03.0_GULP/csssr1116/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:344:32)
`

**Comment by jt3k** [comment]
а есть возможность переразвернуть в папке  без кирилицы в пути ?  например в `/tmp/cssr` ?

**Comment by mathetes** [comment]
Изменил на латиницу
Таже самая ошибка

**Comment by jt3k** [comment]
@mathetes не могли бы вы сказать нам чего выдают эти команды в терминале ?
```bash
npm -v
node -v
uname -a
```

**Comment by mathetes** [comment]
npm -v
3.10.9
node -v
v7.2.0
uname -a
Linux mathetes-s300ca 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Попереключался через nvm на v6.5.0 и более ранних таже ошибка

**Comment by jt3k** [comment]
а что за дистрибутив линуха ?

**Comment by jt3k** [comment]
надо будет попробовать в убунте потестить.

**Comment by Nitive** [comment]
Ещё актуально?

**Comment by jt3k** [comment]
хз . я постоянно забываю потестить )

**Comment by Nitive** [comment]
Закрою пока, если повторится, переоткроем
