### ISSUE TITLE
Ошибка при установке модулей и запуске

### ISSUE THREAD

**Issue by lcf0s** [CSSSR/csssr-project-template#212]
npm i дает:

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
> okidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
> 1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
> )
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\st
> ylint\node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
> 1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
> )
> npm ERR! Windows_NT 6.2.9200
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "i"
> npm ERR! node v6.11.2
> npm ERR! npm  v3.10.10
> npm ERR! path C:\Users\x\Documents\x\csssr-project\node_modules\.staging\gulp-jade-1fb6b4fa\package.json
> npm ERR! code ENOENT
> npm ERR! errno -4058
> npm ERR! syscall open
> 
> npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\x\Documen
> tsx\csssr-project\node_modules\.
> staging\gulp-jade-1fb6b4fa\package.json'
> npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\x\Documen
> ts\x\csssr-project\node_modules\.
> staging\gulp-jade-1fb6b4fa\package.json'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\x\Documents\x\csssr-project\npm-debug.log

при npm start

> > csssr-project-template@0.26.2 start C:\Users\x\Documents\x\csssr-project
> > gulp --debug
> 
> [16:49:57] Failed to load external module babel-register
> [16:49:57] Failed to load external module babel-core/register
> [16:49:57] Failed to load external module babel/register
> module.js:471
>     throw err;
>     ^
> 
> Error: Cannot find module 'require-dir'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\x\Documents\x\cs
> ssr-project\gulpfile.babel.js:3:1)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
> 
> npm ERR! Windows_NT 6.2.9200
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
> node_modules\\npm\\bin\\npm-cli.js" "start"
> npm ERR! node v6.11.2
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! csssr-project-template@0.26.2 start: `gulp --debug`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the csssr-project-template@0.26.2 start script 'gulp --debug'
> .
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the csssr-project-templat
> e package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     gulp --debug
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs csssr-project-template
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls csssr-project-template
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\x\Documents\x\csssr-project\npm-debug.log

как исправить?

**Comment by lcf0s** [comment]
Исправлено глобальной установкой модулей.
