### ISSUE TITLE
Не запускается с последней версией gulp.spritesmith

### ISSUE THREAD

**Issue by in-in** [CSSSR/csssr-project-template#56]
Не запускается с версией [gulp.spritesmith@4.3.0](https://github.com/twolfson/gulp.spritesmith/blob/master/CHANGELOG.md)

```bash
➜  new-project git:(master) gulp
[15:46:42] Requiring external module babel-core/register
[15:46:43] Using gulpfile /media/id/hdd/dev/sites/new-project/gulpfile.babel.js
[15:46:43] Starting 'default'...
[15:46:43] Starting 'stylesDependences'...
[15:46:43] Starting 'sprite'...
[15:46:43] Starting 'templates'...
[15:46:43] Starting 'scripts'...
[15:46:43] Starting 'lint'...
[15:46:43] Finished 'stylesDependences' after 47 ms
[15:46:43] Finished 'default' after 48 ms
/media/id/hdd/dev/sites/new-project/node_modules/spritesmith/src/smith.js:60
    throw new Error('Expected `engine` to have `specVersion` within "' + SPEC_VERSION_RANGE + '" ' +
    ^

Error: Expected `engine` to have `specVersion` within ">=1.1.0 <2.0.0" but it was "undefined". Please verify you are on the latest version of your engine: `npm install my-engine@latest`
    at spritesmith (/media/id/hdd/dev/sites/new-project/node_modules/spritesmith/src/smith.js:60:11)
    at generateNormalSpritesheet (/media/id/hdd/dev/sites/new-project/node_modules/gulp.spritesmith/lib/gulp-spritesmith.js:188:9)
    at /media/id/hdd/dev/sites/new-project/node_modules/gulp.spritesmith/node_modules/async/lib/async.js:567:21
    at /media/id/hdd/dev/sites/new-project/node_modules/gulp.spritesmith/node_modules/async/lib/async.js:246:17
    at /media/id/hdd/dev/sites/new-project/node_modules/gulp.spritesmith/node_modules/async/lib/async.js:122:13
    at _each (/media/id/hdd/dev/sites/new-project/node_modules/gulp.spritesmith/node_modules/async/lib/async.js:46:13)
    at async.each (/media/id/hdd/dev/sites/new-project/node_modules/gulp.spritesmith/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/media/id/hdd/dev/sites/new-project/node_modules/gulp.spritesmith/node_modules/async/lib/async.js:245:13)
    at Object.map (/media/id/hdd/dev/sites/new-project/node_modules/gulp.spritesmith/node_modules/async/lib/async.js:216:23)
    at _parallel (/media/id/hdd/dev/sites/new-project/node_modules/gulp.spritesmith/node_modules/async/lib/async.js:565:20)
    at Object.async.parallel (/media/id/hdd/dev/sites/new-project/node_modules/gulp.spritesmith/node_modules/async/lib/async.js:595:9)
    at DestroyableTransform.onEnd [as _flush] (/media/id/hdd/dev/sites/new-project/node_modules/gulp.spritesmith/lib/gulp-spritesmith.js:185:11)
    at DestroyableTransform.<anonymous> (/media/id/hdd/dev/sites/new-project/node_modules/gulp.spritesmith/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
```

```bash
➜  new-project git:(master) ✗ npm list --depth=0
csssr-project-template@0.11.5 /media/id/hdd/dev/sites/new-project
├── autoprefixer-stylus@0.8.1
├── babel-core@5.8.34
├── babel-eslint@4.1.5
├── babelify@6.4.0
├── bemto.jade@0.2.2
├── browser-sync@2.10.0
├── browserify@11.2.0
├── coffee-script@1.10.0
├── debuga@1.0.2
├── del@2.0.2
├── eslint@1.9.0
├── gulp@3.9.0
├── gulp-bump@1.0.0
├── gulp-cached@1.1.0
├── gulp-changed@1.3.0
├── gulp-csscomb@3.0.6
├── gulp-eslint@1.1.0
├── gulp-filter@3.0.1
├── gulp-gh-pages@0.5.4
├── gulp-group-css-media-queries@1.1.0
├── gulp-html-prettify@0.0.1
├── gulp-if@2.0.0
├── gulp-imagemin@2.4.0
├── gulp-jade@1.1.0
├── gulp-jade-inheritance@0.5.3
├── gulp-minify-css@1.2.1
├── gulp-plumber@1.0.1
├── gulp-rename@1.2.2
├── gulp-stylus@2.1.0
├── gulp-svg-symbols@1.0.0
├── gulp-uglify@1.5.1
├── gulp-util@3.0.7
├── gulp-watch@4.3.5
├── gulp-zip@3.0.2
├── gulp.spritesmith@4.3.0
├── jquery@2.1.4
├── merge-stream@1.0.0
├── pngsmith@0.1.5
├── require-dir@0.3.0
├── run-sequence@1.1.4
├── rupture@0.6.1
├── svg4everybody@2.0.0
├── vinyl-buffer@1.0.0
└── vinyl-source-stream@1.1.0

```

С версией @4.2.4 работает нормально

**Comment by felixexter** [comment]
Временно указали стабильную версию, пока не пофиксили. Будем следить :wink:
