### ISSUE TITLE
Ошибка при запуске проекта

### ISSUE THREAD

**Issue by boxatagit** [CSSSR/csssr-project-template#89]
Запускаю, а мне на это

λ npm start -- --open

> csssr-project-template@0.17.1 start C:\cs
> gulp --debug "--open"

[13:45:19] Requiring external module babel-register
C:\cs\gulp\copy.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at loader (C:\cs\node_modules\babel-register\lib\node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\cs\node_modules\babel-register\lib\node.js:144:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at requireDir (C:\cs\node_modules\require-dir\index.js:116:33)
    at Object.<anonymous> (gulpfile.babel.js:3:1)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\io\\node.exe" "C:\\io\\node_modules\\npm\\bin\\npm-cli.js" "start" "--" "--open"
npm ERR! node v3.3.1
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! csssr-project-template@0.17.1 start: `gulp --debug "--open"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the csssr-project-template@0.17.1 start script 'gulp --debug "--open"'.
npm ERR! This is most likely a problem with the csssr-project-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --debug "--open"
npm ERR! You can get their info via:
npm ERR!     npm owner ls csssr-project-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cs\npm-debug.log

Что делать, где туплю?

**Comment by dzhiriki** [comment]
Обновите шаблон. Вчера эта ошибка была поправлена.

**Comment by boxatagit** [comment]
Обновил. Спасибо, эта проблема решилась.
Но теперь новая напасть.

λ npm start -- --open

> csssr-project-template@0.17.1 start C:\cs
> gulp --debug "--open"

[14:34:03] Requiring external module babel-register
C:\cs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:393
          throw new Error("Couldn't find preset " + JSON.stringify(val) + " relative to directory " + JSON.stringify(dirname));
          ^

Error: Couldn't find preset "es2015" relative to directory "C:\\cs"
    at C:\cs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:393:17
    at Array.map (native)
    at OptionManager.resolvePresets (C:\cs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:385:20)
    at OptionManager.mergePresets (C:\cs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:369:10)
    at OptionManager.mergeOptions (C:\cs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:328:14)
    at OptionManager.addConfig (C:\cs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:10)
    at OptionManager.findConfigs (C:\cs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:434:16)
    at OptionManager.init (C:\cs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:489:12)
    at compile (C:\cs\node_modules\babel-register\lib\node.js:91:26)
    at loader (C:\cs\node_modules\babel-register\lib\node.js:134:14)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\io\\node.exe" "C:\\io\\node_modules\\npm\\bin\\npm-cli.js" "start" "--" "--open"
npm ERR! node v3.3.1
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! csssr-project-template@0.17.1 start: `gulp --debug "--open"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the csssr-project-template@0.17.1 start script 'gulp --debug "--open"'.
npm ERR! This is most likely a problem with the csssr-project-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --debug "--open"
npm ERR! You can get their info via:
npm ERR!     npm owner ls csssr-project-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cs\npm-debug.log

**Comment by iamstarkov** [comment]
переустанови зависимости и запусти снова
```
$ rm -rf node_modules
$ npm install
$ npm start -- --open
```

**Comment by dzhiriki** [comment]
@boxatagit Можете уточнить, совет помог? Всё заработало?

**Comment by boxatagit** [comment]
Прошу прощения. Увлёкся гуглом.
Совет про "переустановить" не помог.
Так что по прежнему рад любым идеям.

**Comment by in-in** [comment]
> npm ERR! node v3.3.1
npm ERR! npm v2.14.3

Есть возможность обновить?

**Comment by boxatagit** [comment]
Обновил. Всё заработало.
Огромное спасибо за помощь и участие!
